#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
        . /usr/share/dbconfig-common/dpkg/config.mysql
        if ! dbc_go phpmyadmin $@ ; then
            echo 'Automatic configuration using dbconfig-common failed!'
        fi
fi

db_version 2.0

db_input high phpmyadmin/reconfigure-webserver || true

if [ ! -f /etc/phpmyadmin/htpasswd.setup ]; then
	db_input low phpmyadmin/setup-username || true
	db_input low phpmyadmin/setup-password || true
fi

db_go || true

