.TH PMA-SECURE 8 "October 14, 2009"
.SH NAME
pma\-secure \- secures phpMyAdmin installation
.SH SYNOPSIS
.B pma\-secure
.SH DESCRIPTION
pma\-secure changes permissions on the configuration file of phpMyAdmin,
so that the setup script (usually installed as
<http://localhost/phpmyadmin/setup/index.php>)
can not write to it.
.SH OPTIONS
This program does not accept any command line parameters.
.SH SEE ALSO
/usr/share/doc/phpmyadmin/README.Debian

pma\-configure(8)
.SH AUTHOR
This manual page and the script were written by Michal Cihar
<nijel@debian.org>.
