.TH PMA-CONFIGURE 8 "October 14, 2009"
.SH NAME
pma\-configure \- enables configuration of phpMyAdmin installation
.SH SYNOPSIS
.B pma\-configure
.SH DESCRIPTION
pma\-configure changes permissions on the configuration file of phpMyAdmin,
so that the setup script (usually installed as
<http://localhost/phpmyadmin/setup/index.php>) can write to it.
.PP
.B Please note that having the system in this state may be insecure.
Remember to run pma\-secure(8) after you are done with configuration.
.SH OPTIONS
This program does not accept any command line parameters.
.SH SEE ALSO
/usr/share/doc/phpmyadmin/README.Debian

pma\-secure(8)
.SH AUTHOR
This manual page and the script were written by Michal Cihar
<nijel@debian.org>.
