Installation Methods
====================

You can install Aguilas in various ways, depending on your requirements. Here you will find all the supported installation methods. In any case, you will need to `install software dependencies <dependencies.rest>`_ before you can actually install Aguilas.

Using the Makefile
------------------

#. Download the source tarball from `aguilas download page <http://code.google.com/p/aguilas/downloads/list>`_. Select the version of your preference, usually the last one will be more complete.

   You can also clone the code directly from the "release" (stable) branch of the git repository (if you do, you don't need to decompress the source after)::

	git clone --branch release https://github.com/HuntingBears/aguilas.git

#. Decompress the source with your favorite program::

	e.g.: tar -xvf aguilas-1.0.0.tar.gz

#. Access the uncompressed source::

	e.g.: cd aguilas-1.0.0/

#. Build the sources::

	make


  You will be promted with the following questions to configure AGUILAS:
    + Name of the Application
    + The person or group responsible for managing the application
    + The e-mail address that will appear as sender in all operation e-mails to registered users
    + The e-mail address you wish to use for sending error reports
    + The language that you wish to see in your application
    + The theme applied to the application
    + The public address of the aplication
    + IP or Domain of the server where the MYSQL database is located
    + MYSQL database name
    + User with permissions to read and create tables on the database
    + Password for the MYSQL user
    + IP or Domain of the server where the LDAP service is located
    + DN with read-write priviledges on the LDAP server
    + Password for the writer DN
    + Base DN to perform searches and include new users

  If you need to modify these parameters, you can always edit ``/usr/share/aguilas/setup/config.php`` after installation.

#. Obtain superuser priviledges, and install aguilas::

	sudo make install

Using a package from a distribution
-----------------------------------



Installing the development version
----------------------------------

