#!/bin/bash -e

CONFFILE="/etc/aguilas/config.php"

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

# Autoconfiguration for aguilas
if [ ! -f ${CONFFILE} ] || [ $( md5sum ${CONFFILE} | awk '{print $1}' ) = "FIXME" ]; then

	# Let's try to read default from slapd.conf, libnss-ldap.conf or libpam_ldap.conf
	if [ -f /etc/ldap/slapd.conf ]; then

		LDAPSERVER="localhost"

		if grep "^TLS" /etc/ldap/slapd.conf > /dev/null 2>&1; then
			LDAPTLS="true"
		else
			LDAPTLS="false"
		fi

		BASEDN=$( grep ^suffix /etc/ldap/slapd.conf | awk '{print $2}' | sed -e s/\"//g )
		BINDDN=$( grep -e "by dn=.* write" /etc/ldap/slapd.conf | cut -d"\"" -f2 | head -n1 )

	elif [ -f /etc/libnss-ldap.conf ]; then

		if grep "^host" /etc/libnss-ldap.conf > /dev/null 2>&1; then
			LDAPSERVER=$( grep ^host /etc/libnss-ldap.conf | awk '{print $2}' )
		elif grep "^uri" /etc/libnss-ldap.conf > /dev/null 2>&1; then
			LDAPSERVER=$( grep ^uri /etc/libnss-ldap.conf | sed -e s@/@@g | awk -F : '{print $2}' )
		fi

		if grep "^TLS" /etc/libnss-ldap.conf > /dev/null 2>&1; then
			LDAPTLS="true"
		else
			LDAPTLS="false"
		fi

		BASEDN=$( grep -e "^base" /etc/libnss-ldap.conf | awk '{print $2}' | sed -e s/\"//g )
		BINDDN=$( grep -e "^rootbinddn" /etc/libnss-ldap.conf | awk '{print $2}' )

	elif [ -f /etc/pam_ldap.conf ]; then

		if grep "^host" /etc/pam_ldap.conf > /dev/null 2>&1; then
			LDAPSERVER=$( grep ^host /etc/pam_ldap.conf | awk '{print $2}' )
		elif grep "^uri" /etc/pam_ldap.conf > /dev/null 2>&1; then
			LDAPSERVER=$( grep ^uri /etc/pam_ldap.conf | sed -e s@/@@g | awk -F : '{print $2}' )
		fi

		if grep "^TLS" /etc/pam_ldap.conf > /dev/null 2>&1; then
			LDAPTLS="true"
		else
			LDAPTLS="false"
		fi

		BASEDN=$( grep -e "^base" /etc/pam_ldap.conf | awk '{print $2}' | sed -e s/\"//g )
		BINDDN=$( grep -e "^rootbinddn" /etc/pam_ldap.conf | head -n1 | awk '{print $2}' )

	fi

	if [ -f /etc/ldap.secret ]; then
		BINDPW=$( head -n1 /etc/ldap.secret )
	fi

	db_input medium aguilas/app-mail || true
	db_go || true
	db_get aguilas/app-mail || true
	APPMAIL="${RET}"
	db_set aguilas/app-mail ${APPMAIL} || true

	db_input medium aguilas/app-url || true
	db_go || true
	db_get aguilas/app-url || true
	APPURL="${RET}"
	db_set aguilas/app-url ${APPURL} || true

	if [ -z ${LDAPSERVER} ]; then
		db_input medium aguilas/ldap-server || true
		db_go || true
		db_get aguilas/ldap-server || true
		LDAPSERVER="${RET}"
	fi

	db_set aguilas/ldap-server ${LDAPSERVER} || true

	if [ -z ${LDAPTLS} ]; then
		db_input medium aguilas/ldap-tls || true
		db_go || true
		db_get aguilas/ldap-tls || true
		LDAPTLS="${RET}"
	fi

	db_set aguilas/ldap-tls ${LDAPTLS} || true

	db_input medium aguilas/ldap-enc || true
	db_go || true
	db_get aguilas/ldap-enc || true
	LDAPENC="${RET}"
	db_set aguilas/ldap-enc ${LDAPENC} || true

	if [ "${LDAPTLS}" == "true" ]; then
		LDAPSERVER="ldaps:\\/\\/${LDAPSERVER}"
		db_set aguilas/ldap-server ${LDAPSERVER} || true
	fi

	if [ -z ${BASEDN} ]; then
		db_input medium aguilas/ldap-basedn || true
		db_go || true
		db_get aguilas/ldap-basedn || true
		BASEDN="${RET}"
	fi

	db_set aguilas/ldap-basedn ${BASEDN} || true
	
	if [ -z ${BINDDN} ]; then
		db_set aguilas/ldap-binddn "cn=admin,${BASEDN}"
		db_input medium aguilas/ldap-binddn || true
		db_go || true
		db_get aguilas/ldap-binddn || true
	fi

	db_set aguilas/ldap-binddn ${BINDDN} || true

	if [ -z ${BINDPW} ]; then
		db_input medium aguilas/ldap-bindpw || true
		db_go || true
		db_get aguilas/ldap-bindpw || true
	fi

	db_set aguilas/ldap-bindpw ${BINDPW} || true

	db_input medium aguilas/reconfigure-webserver || true
	db_go || true
	db_get aguilas/reconfigure-webserver || true
	WEBSERVERS="${RET}"
	db_set aguilas/reconfigure-webserver ${WEBSERVERS} || true

	if [ -n ${WEBSERVERS} ]; then
		db_input medium aguilas/restart-webserver || true
		db_go || true
		db_get aguilas/restart-webserver || true
		RESTART="${RET}"
		db_set aguilas/restart-webserver ${RESTART} || true
	fi

fi

#DEBHELPER#

exit 0
