#!/bin/bash
#
# ====================================================================
# PACKAGE: aguilas
# FILE: tools/predoc.sh
# DESCRIPTION:	build: Replaces @@DATA@@ tokens with correct values
#		on documentation and generates proper output files.
#		clean: Cleans output files generated by build.
# USAGE: ./tools/predoc.sh [build] [clean]
# COPYRIGHT:
# (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCE: GPL3
# ====================================================================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# COPYING file for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# CODE IS POETRY

ROOTDIR="$( pwd )"
DOCDIR="${ROOTDIR}/documentation"
RESTDIR="${DOCDIR}/rest"
VERSIONFILE="${ROOTDIR}/VERSION"
INFILES=$( grep -R "@@.*@@" ${DOCDIR} | awk -F: '{print $1}' | sort -u | grep "^.*\.in$" )
OUTFILES=$( grep -R "@@.*@@" ${DOCDIR} | awk -F: '{print $1}' | sort -u | grep "^.*\.in$" | sed 's|\.in$||g' )
SUBS="AUTHOR DATE VERSION URL DESCRIPTION DESCRIPTIONLINES COMMONINTRO RSTLIST LINKLIST"
AUTHOR="Luis Alejandro Martínez Faneyth"
DATE=$( date +%d-%m-%Y )
VERSION=$( cat ${VERSIONFILE} | grep "VERSION = " | sed 's/VERSION = //g;s/+.*//g' )
URL="http://code.google.com/p/aguilas"
DESCRIPTION="A web-based LDAP user management system"
DESCRIPTIONLINES="---------------------------------------"
COMMONINTRO=$( cat ${DOCDIR}/common.index.in | sed ':a;N;$!ba;s/\n/______/g' )
RSTLIST=$( ls ${RESTDIR}/*.rest | sed "s|${RESTDIR}/|@@@@@@|g" | sed ':a;N;$!ba;s|\n||g' )
LINKLIST=$( ls ${RESTDIR}/*.rest | sed "s|${RESTDIR}/|######|g;s|.rest|%%%%%%|g;" | sed ':a;N;$!ba;s|\n||g' )

case ${1} in

build)

	for INFILE in ${INFILES}; do

		OUTFILE=$( echo ${INFILE} | sed 's|\.in$||g')
		cp ${INFILE} ${OUTFILE}

		for SUB in ${SUBS}; do
			sed -i "s|@@${SUB}@@|$( eval "echo \"\$${SUB}\"" )|g" ${OUTFILE}
			sed -i "s|______|\n|g;s|@@@@@@|\n\ \ \ |g;s|######|\n[[|g;s|%%%%%%|]]|g" ${OUTFILE}
		done
	done
;;

clean)

	for OUTFILE in ${OUTFILES}; do
		rm -rf ${OUTFILE}
	done
;;

esac
